### PR TITLE
11 suggestion stubs

### PR DESCRIPTION
**Pull request by brentongk**
Please review the stub classes for the Suggestion subsystem.

### CODE REVIEW

**Comment by yo09975** [comment]
Commit f705e1b is unrelated to this ticket. Remove it.

**Comment by patmay** [comment]
The actual code looks pretty good, but there are a few things I'd like cleaned up. I'm being particularly picky because we're early in development.

Both files should be located in a src directory.

In both classes, you're creating two attrs for each one attr you actually want. One is static to the class and is never referenced, the other is the instance attr that you actually want. This code will run correctly, but the static attr is extraneous and might cause confusion to some developers.


 ```
class Suggestion:
        _name = None // This creates a class (static) attribute Suggestion._name which is never used
 
 	def __init__(self, name: str, room: Card, weapon: Card, character: Card):
 		self._name = name // This creates an instance attribute self._name
```

Neither Suggestion nor SuggestionEngine needs a _name attr (static or instance).

I don't think the SuggestionEngine should be accessing the MovementEngine, that should probably be left to the GameController (encapsulation). I'm not entirely sure what make_suggestion() should do...

Finally, I suggest you make two classes, one SuggestionEngineStub, which extends SuggestionEngine and returns dummy values. This will allow you to work on SuggestionEngine while others use SEStub for testing, etc.

**Comment by brentongk** [comment]
I've implemented your suggestions @patmay , let me know if there is anything else missing! Thanks!

**Comment by patmay** [comment]
Almost! Please remove the self._name references from suggestion and suggestionengine _init_, and rename the stub classes (not just filenames) from SuggestionEngine to SuggestionEngineStub and Suggestion to SuggestionStub. I think having conflicting class will cause problems.

Also, the second line in this should be removed, but I won't let it hold up a PR since it doesn't do any harm.
```
class Suggestion:

	_suggestion_set = None // Remove these variables, as they are static class references

	def __init__(self, room: Card, weapon: Card, character: Card):
```

**Comment by brentongk** [comment]
@patmay should be resolved left me know if I missed anything else, thanks sir!

**Comment by patmay** [comment]
Edits look good. I approve.

**Review by patmay — APPROVED** [review]

**Pull request merged**
