### PR TITLE
131 suggestion and card equality

### PR DESCRIPTION
**Pull request by brentongk**
These are the changes to add equality check methods to both Card and Suggestion.

### CODE REVIEW

**Comment by yo09975** [comment]
Please connect PRs with the appropriate issue

**Comment by yo09975** [comment]
Your approach is how I originally intended to implement my changes as well. I found the solution from:
https://stackoverflow.com/questions/390250/elegant-ways-to-support-equivalence-equality-in-python-classes

to work well for our purposes. Drop the commit for card equality, change the suggestion equality check, make sure we're not crazy, and resubmit.

**Comment by brentongk** [comment]
I've made the changes you requested and it looks good!

**Review by yo09975 — APPROVED** [review]
I think we should incorporate unit tests for the __eq__ overrides for any class that uses one. This method seemed to work for the other classes so we can add the test later if there is time.

**Pull request merged**
