### PR TITLE
08 gamemanagement

### PR DESCRIPTION
**Pull request by stephensmeal**
Please review stubbing of Game Management classes.

### CODE REVIEW

**Comment by patmay** [comment]
Remove static/class attributes.

I think you can remove the CardType class by doing the following:

```
class Card(object, Enum):
    SUSPECT = 1
     ROOM = 2
     WEAPON = 3
...
```

GameState and GameController - questionable use of static attrs, but not deal breaking.

In Card, I'm not sure what this does. I presume it returns a boolean expressue 
`return (card in self._cards)`

In Location and Hall, great use of error checking/validation.

For some of the classes, you might want to create a ClassStub class, so that people can use your stub while you write the real deal.

**Comment by stephensmeal** [comment]
Remove static/class attributes.
-- I don't think it really matters considering all of the attributes are changed with the constructor and I think it's easier to read like how Java code declares the variables before methods but since this is the second time you've mentioned it I'll take them out.

I think you can remove the CardType class by doing the following:

class Card(object, Enum):
    SUSPECT = 1
     ROOM = 2
     WEAPON = 3
...
-- This doesn't work. I tried it several different ways since the other day when you said about it also. The way you have written gives the following error:
"smealMacbook:GameManagemetSystem stevesmeal$ python card.py
Traceback (most recent call last):
  File "card.py", line 4, in <module>
    class Card(object, Enum):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/enum.py", line 153, in __new__
    enum_class = super().__new__(metacls, cls, bases, classdict)
TypeError: Cannot create a consistent method resolution
order (MRO) for bases object, Enum"
If anyone can figure out another way to implement it let me know. I'm all ears.

GameState and GameController - questionable use of static attrs, but not deal breaking.
-- If your first comment is to remove declaring attributes at the beginning then this should also be held to the same standard so I'll remove them.

In Card, I'm not sure what this does. I presume it returns a boolean expressue
return (card in self._cards)
-- Yes, that's a common feature of Python.

In Location and Hall, great use of error checking/validation.

For some of the classes, you might want to create a ClassStub class, so that people can use your stub while you write the real deal.
--  I will work on ClassStub classes.

**Comment by patmay** [comment]
tl;wr: Keep CardType

I was able to get rid of your error by removing the inheritance from object:
`class Card(Enum)
`
However, this creates another error with the constructor. According to the Enum docs, if you define an __init__ for a subclass of Enum, it will pass the value of the Enum (in your case, 1, 2, or 3) to that initializer. Because we want different parameters, this either wont work or would need to be messy. I think you'd also run into issue if we try to further subclass Card. To keep things simple, I think having a separate class of CardType would be best.

**Comment by patmay** [comment]
I believe GameController's init variables are local, not class or instance. Probably should be instance (self.attr). Since we're only stubbing, I'll merge, but be sure to revisit down the road.

Potential design doc problem, GameState get player might need to return a Player object instead of int. It uses an internal Int to figure who it is, but I think any class accessing GameState wants a person.

Potential design doc question: should add_/remove_occupant return true or false for success? I like your error handling, but there's no way to take advantage of it outside of testing.

Your commenting/documentation is excellent.

**Comment by patmay** [comment]
Actually, you're asking to merge into master. I will not do that. Waiting for @yo09975 to address question on how to proceed.

**Review by patmay — APPROVED** [review]

**Pull request merged**
