### PR TITLE
07 note card stubs

### PR DESCRIPTION
**Pull request by brentongk**
@patmay please review this PR!

### CODE REVIEW

**Comment by patmay** [comment]
These classes do not need name attributes. Please remove them.

Please also remove the symbol param in notecard as it does not align with the design doc.

NoteCard's mark() function wills simply do (in pseudocode)
`note_state[x][y] = (note_state[x][y] + 1) % NUMBER_OF_MARKS
`

**Comment by brentongk** [comment]
@patmay Done! Sorry about that, still wrapping my head around those. Let me know if you see anything else!

**Comment by patmay** [comment]
Because it's pseudocode, please comment it out and resubmit. Otherwise, it will break.

**Comment by brentongk** [comment]
@patmay Done!

**Comment by patmay** [comment]
Approved for merge into integ, though NoteCardStub still has reference to parameter symbol.

**Review by patmay — APPROVED** [review]

**Comment by brentongk** [comment]
@yo09975 let me know if you will be able to merge this today, thanks sir!

**Comment by yo09975** [comment]
This branch can't be merged until it is rebased on integ (despite what the GUI says -- we're avoiding merge commits coming in on feature branches). There are commits from the suggestion management branch that need to be removed and a change to the README that fails to apply. 

The easiest way to fix this branch is to just copy the changes you want to some other directory, delete the branch, branch again from integ, and copy/commit your changes again.

**Pull request closed without merging**
